# Directory to the training set (contains state_data.csv and images directory)
test_dir: 'C:\Users\sambu\Documents\Repositories\CodeBases\SWiMM_DEEPeR\data\cmvae_test_set\64x64'

# Path to the trained models checkpoint (requires .index and data file)
weights_path: 'C:\Users\sambu\Documents\Repositories\CodeBases\SWiMM_DEEPeR\models\cmvae\0\best_model\model.ckpt'

# Directory to the interpolated set (contains state_data.csv and images directory)
interpolation_dir: 'C:\Users\sambu\Documents\Repositories\CodeBases\SWiMM_DEEPeR\data\cmvae_interpolation\64x64'