# Should we exclusively use cpu
use_cpu_only: False

# Number of features to encode down to
n_z: 10

# If using image obs, declare desired output size of scaling function
img_res: [64,64,3]

# Should we use latent space constraints (i.e. CmvaeDirect)
latent_space_constraints: True

# Do we want to run deterministic operations (e.g. for reproducibility)
deterministic: True
