UnderwaterEnv:
  - gym_underwater.callbacks.SwimEvalCallback:
#        callback_after_eval:
#          stable_baselines3.common.callbacks.StopTrainingOnNoModelImprovement:
#            max_no_improvement_evals: 5
#            min_evals: 0
#            verbose: 1
#        callback_on_new_best:
#          stable_baselines3.common.callbacks.StopTrainingOnRewardThreshold:
#            reward_threshold: 2500
#            verbose: 1
        eval_inference_freq: [100, 'episode']
        eval_freq: 10
        min_train_steps: 500000
        deterministic: True
        verbose: 1
  - gym_underwater.callbacks.SwimCallback