## THIS FILE CONTAINS ALL THE TRAINING/INFERENCE PARAMETERS AND GYM ENVIRONMENT PARAMETERS  ###
## THE FOLLOWING ARE GLOBAL PARAMETERS  ###
# Observation type. CHOICES: 'image', 'vector', 'cmvae'
obs: 'cmvae'

# If you want to pass image observation through pretrained encoder, provide filepath, else pass empty string
cmvae_path: 'C:\Users\sambu\Documents\Repositories\CodeBases\SWiMM_DEEPeR\data\cmvae_training_seed_2\results_seed_2_device_gpu\best_model.ckpt'

# If using image obs, declare desired output size of scaling function. NOTE this is DIFFERENT from cmvae img_res, which uses img_res contained in cmvae_config.
img_res: !!python/tuple [64,64,3]

# Do we want to output the packet information and save images
debug_logs: True

# Set seed with arbitrary int so that can report with results this also sets the seed on the simulation
# Appended to server_config.json
seed: 3

### THE FOLLOWING ARE TRAINING PARAMETERS  ###
# Algorithm to import from Stable Baselines. CHOICES: 'sac', 'ppo', 'ddpg'
algo: 'sac'

# If you want to train on top of an existing model, provide filepath, else pass empty string
model_path: ''

# Absolute distance from optimal tracking position.
# Appended to server_config.json
opt_d: 6.0

# Maximum deviation allowed from opt_d before an episode is reset.
# Appended to server_config.json
max_d: 4.0

### THE FOLLOWING ARE INFERENCE PARAMETERS  ###
# Path to where to create reward log csv as an output of inference run
reward_log_path: 'C:\Users\sambu\Documents\Repositories\CodeBases\SWiMM_DEEPeR\Logs\sac\1\inference.csv'