#This file contains all the run parameters and Gym environment parameters. This is different to the algorithm hyperparameters,
#which are stored in the yaml file associated with the chosen algorithm, in the 'hyperparams' folder.

# The following are run parameters

# Algorithm to import from Stable Baselines. CHOICES: 'sac', 'ddpg', 'ppo'
algo: 'sac'

# If want to train on top of an existing model, provide filepath, else pass empty string
model: ''

# If want to pass image observation through pretrained encoder, provide filepath, else pass empty string
vae_path: ''

# Whether or not to use Tensorboard NOTE: resulting event files are large
tb: True

# Whether to save the Monitor logs generate by the Stable Baselines Monitor wrapper NOTE: False still writes but to tmp
monitor: True

# Override log interval (default: -1, no change)
log_interval: -1

# Verbose mode (0: no output, 1: INFO)
verbose: 1

# set seed with arbritrary int so that can report with results
seed: 31

# The following are environment parameters

# Observation type. CHOICES: 'image', 'vector', 'vae'
obs: 'vector'

# If using image obs, declare desired output size of scaling function
img_scale: !!python/tuple [ 84,84,3]

# Used to express the optimal tracking position. This value is subtracted from the z-coordinate of the target's position 
# i.e. how far set back from the target do you want the AUV to position itself
opt_d: 10

# At what radial distance should the episode terminate (FROM THE OPTIMAL TRACKING POSITION, NOT THE TARGET POSITION)
max_d: 30

# Do we want to ouput the packet information and save images
debug_logs: True