UnderwaterEnv:
  n_timesteps: !!float 1000000
  policy: 'CnnPolicy' 
  learning_rate: acc_3e-4
  buffer_size: 30000
  batch_size: 64
  train_freq: 3000
  gamma: 0.99
  ent_coef: 'auto_0.05'
  gradient_steps: 600
  learning_starts: 300

