UnderwaterEnv:
  n_timesteps: !!float 1000
  policy: 'CnnPolicy' 
  learning_rate: !!float 3e-4
  buffer_size: 30000
  batch_size: 64
  train_freq: 100
  gamma: 0.99
  ent_coef: 0
  gradient_steps: 600
  learning_starts: 3000

